### ISSUE TITLE
Dropdown menu

### ISSUE THREAD

**Issue by luetkemj** [luetkemj/scribe#110]
Make drop down menu in header as opposed to the sidebar we have currently.

- [x] design
- [ ] component #113 
- [ ] actions #114 
- [ ] reducer #114
- [ ] container #115

**Comment by luetkemj** [comment]
<img width="222" alt="screen shot 2016-12-04 at 7 35 16 pm" src="https://cloud.githubusercontent.com/assets/925980/20871207/cee8b966-ba58-11e6-8d91-92be12eb9b07.png">

**Comment by streeetlamp** [comment]
Will this totally remove the sidebar or is that used for other things?

**Comment by luetkemj** [comment]
That's the plan - but I'm not entirely sure what will go in it's place. I need to talk with some UX folks at work in order to have a more long term plan on the features.
