### ISSUE TITLE
Where can I help?

### ISSUE THREAD

**Issue by streeetlamp** [luetkemj/scribe#122]
Off the entire week and maybe in the mood for JS, assign me something 

![giphy](https://cloud.githubusercontent.com/assets/1740634/21506267/c80658ce-cc3c-11e6-947f-4af696db6d26.gif)

**Comment by luetkemj** [comment]
Woot!

The dropdown menu #110 is probably the most straight forward. It needs all the pieces (or as many as you find are actually required).

If you want to do API stuff though you could help with the time or weather APIs but we would need to sync as they are a lot more complex and I haven't really detailed things here.

Some other UI upgrades on the campaign logger too if you want to do UX stuff.

**Comment by luetkemj** [comment]
@streeetlamp I updated dependencies this am on #123  - make sure to pull that and do a clean install before doing any work :)

**Comment by streeetlamp** [comment]
@luetkemj hey im obviously god awful at responding to things but i would like to help when it hits me/have time. maybe under one of your projects if you had a column you could throw things that you think would be useful for me to tackle without poking at you and i wont have to bother you (as much) hopefully? did that make sense? WP trac development tags certain things as like 'Good First Bugs'. 

And a gif for your time

![giphy](https://cloud.githubusercontent.com/assets/1740634/22041076/68cb52f4-dcd3-11e6-9129-e46210aa2d41.gif)

**Comment by luetkemj** [comment]
Yeah, I can do that - would be good to have a big old list of small bugs I need to work on anyways :)

**Comment by luetkemj** [comment]
@streeetlamp: I added some good starter issues [here](https://github.com/luetkemj/scribe/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
